apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJiR1YyYVd0aGR6cG5hSEJmYldjNVpXNDFZV2xFVkZodVNHVjVjMDVTWVdwRWQzUjVNelJSV1hCNE1sVlpiamxJIgogICAgfQogIH0sCiAgImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCiAgImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiLAogICJwbHVnaW5zIjogewogICAgIi14LWNsaS1oaW50cyI6IHsKICAgICAgImVuYWJsZWQiOiAidHJ1ZSIKICAgIH0KICB9LAogICJmZWF0dXJlcyI6IHsKICAgICJob29rcyI6ICJ0cnVlIgogIH0KfQo=
type: kubernetes.io/dockerconfigjson
